language: node_js
node_js: 10
sudo: false

cache:
  - node_modules
  - yarn
# before_install:
#   - sudo apt install -y python make gcc libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
#   - sudo apt install -y wine-stable
script:
  - set -e
  - yarn lint
  - yarn test-ci
  - yarn tsc --noEmit
  - |
    if [[ $TRAVIS_BRANCH == "master" ]]; then
      yarn build
      BUILT_TESTS=1 yarn built-test-ci
    fi
  # - if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && . .travis.sh; else echo "$PROJECT is NOT being built"; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
# addons:
#   apt:
#     update: true
